version: '3.5'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: "postgres"
      DB_NAME: "api-payment"
      DB_USER: "api-payment"
      DB_PASS: "api-payment"
      DB_PORT: "5432"
      APP_PORT: "8080"
    restart: always

  postgres:
    image: postgres:10.4-alpine
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: api-payment
      POSTGRES_USER: api-payment
      POSTGRES_PASSWORD: api-payment
