// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import domains "github.com/lucaspizzo/api-payment/domains"
import mock "github.com/stretchr/testify/mock"

// AccountQuerier is an autogenerated mock type for the AccountQuerier type
type AccountQuerier struct {
	mock.Mock
}

// FindAll provides a mock function with given fields: list
func (_m *AccountQuerier) FindAll(list *[]*domains.Account) error {
	ret := _m.Called(list)

	var r0 error
	if rf, ok := ret.Get(0).(func(*[]*domains.Account) error); ok {
		r0 = rf(list)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetById provides a mock function with given fields: id, model
func (_m *AccountQuerier) GetById(id uint64, model *domains.Account) error {
	ret := _m.Called(id, model)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, *domains.Account) error); ok {
		r0 = rf(id, model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Insert provides a mock function with given fields: model
func (_m *AccountQuerier) Insert(model *domains.Account) error {
	ret := _m.Called(model)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domains.Account) error); ok {
		r0 = rf(model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: model
func (_m *AccountQuerier) Update(model *domains.Account) error {
	ret := _m.Called(model)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domains.Account) error); ok {
		r0 = rf(model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
