// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import gin "github.com/gin-gonic/gin"
import mock "github.com/stretchr/testify/mock"

// Accounter is an autogenerated mock type for the Accounter type
type Accounter struct {
	mock.Mock
}

// ListAccount provides a mock function with given fields: ctx
func (_m *Accounter) ListAccount(ctx *gin.Context) {
	_m.Called(ctx)
}

// RegisterAccount provides a mock function with given fields: ctx
func (_m *Accounter) RegisterAccount(ctx *gin.Context) {
	_m.Called(ctx)
}

// RetrieveAccount provides a mock function with given fields: ctx
func (_m *Accounter) RetrieveAccount(ctx *gin.Context) {
	_m.Called(ctx)
}

// UpdateLimits provides a mock function with given fields: ctx
func (_m *Accounter) UpdateLimits(ctx *gin.Context) {
	_m.Called(ctx)
}
