// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import domains "github.com/lucaspizzo/api-payment/domains"
import mock "github.com/stretchr/testify/mock"

// OperationTypeQuerier is an autogenerated mock type for the OperationTypeQuerier type
type OperationTypeQuerier struct {
	mock.Mock
}

// GetById provides a mock function with given fields: id, model
func (_m *OperationTypeQuerier) GetById(id uint64, model *domains.OperationType) error {
	ret := _m.Called(id, model)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, *domains.OperationType) error); ok {
		r0 = rf(id, model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
