// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import domains "github.com/lucaspizzo/api-payment/domains"
import mock "github.com/stretchr/testify/mock"

// OperationTypeContract is an autogenerated mock type for the OperationTypeContract type
type OperationTypeContract struct {
	mock.Mock
}

// Get provides a mock function with given fields: id
func (_m *OperationTypeContract) Get(id uint64) (*domains.OperationType, error) {
	ret := _m.Called(id)

	var r0 *domains.OperationType
	if rf, ok := ret.Get(0).(func(uint64) *domains.OperationType); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domains.OperationType)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
