// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import forms "github.com/lucaspizzo/api-payment/forms"
import mock "github.com/stretchr/testify/mock"

// PaymentContract is an autogenerated mock type for the PaymentContract type
type PaymentContract struct {
	mock.Mock
}

// RegisterPayments provides a mock function with given fields: form
func (_m *PaymentContract) RegisterPayments(form *[]*forms.PaymentForm) error {
	ret := _m.Called(form)

	var r0 error
	if rf, ok := ret.Get(0).(func(*[]*forms.PaymentForm) error); ok {
		r0 = rf(form)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
