// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import gin "github.com/gin-gonic/gin"
import mock "github.com/stretchr/testify/mock"

// Transactioner is an autogenerated mock type for the Transactioner type
type Transactioner struct {
	mock.Mock
}

// AddTransaction provides a mock function with given fields: ctx
func (_m *Transactioner) AddTransaction(ctx *gin.Context) {
	_m.Called(ctx)
}
