// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import domains "github.com/lucaspizzo/api-payment/domains"
import mock "github.com/stretchr/testify/mock"

// TransactionQuerier is an autogenerated mock type for the TransactionQuerier type
type TransactionQuerier struct {
	mock.Mock
}

// FindAll provides a mock function with given fields: list
func (_m *TransactionQuerier) FindAll(list *[]*domains.Transaction) error {
	ret := _m.Called(list)

	var r0 error
	if rf, ok := ret.Get(0).(func(*[]*domains.Transaction) error); ok {
		r0 = rf(list)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAllByAccountId provides a mock function with given fields: list, accountID
func (_m *TransactionQuerier) FindAllByAccountId(list *[]*domains.Transaction, accountID uint64) error {
	ret := _m.Called(list, accountID)

	var r0 error
	if rf, ok := ret.Get(0).(func(*[]*domains.Transaction, uint64) error); ok {
		r0 = rf(list, accountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetById provides a mock function with given fields: id, model
func (_m *TransactionQuerier) GetById(id uint64, model *domains.Transaction) error {
	ret := _m.Called(id, model)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, *domains.Transaction) error); ok {
		r0 = rf(id, model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Insert provides a mock function with given fields: model
func (_m *TransactionQuerier) Insert(model *domains.Transaction) error {
	ret := _m.Called(model)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domains.Transaction) error); ok {
		r0 = rf(model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: model
func (_m *TransactionQuerier) Update(model *domains.Transaction) error {
	ret := _m.Called(model)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domains.Transaction) error); ok {
		r0 = rf(model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
